apiVersion: v2
name: rearm-helm
description: ReARM Helm chart for Kubernetes

type: application

version: 0.3.15

appVersion: "26.01.14"

dependencies:
- name: postgresql
  version: 0.1.0
  repository: oci://registry.relizahub.com/library
  condition: postgresql.enabled