apiVersion: v2
name: rearm-helm
description: ReARM Helm chart for Kubernetes

type: application

version: 0.3.6

appVersion: "25.11.9"

dependencies:
- name: postgresql
  version: 0.1.0
  repository: oci://registry.relizahub.com/library
  condition: postgresql.enabled